import { useState } from "react";

export default function Demo() {
  const [docType, setDocType] = useState("Business Proposal");
  const [language, setLanguage] = useState("English");
  const [companyName, setCompanyName] = useState("");
  const [clientName, setClientName] = useState("");
  const [details, setDetails] = useState("");
  const [result, setResult] = useState("");

  function generateDemo() {
    const text = `
${docType.toUpperCase()} (${language})

Company: ${companyName || "[Your company name]"}
Client: ${clientName || "[Client name]"}

Details:
${details || "[Describe your project, deadlines, pricing, etc.]"}

This is a demo template generated by DocPilot AI.
Upgrade to access UK legal templates and DOCX export.
    `;

    setResult(text.trim());
  }

  return (
    <div style={{ maxWidth: 900, margin: "60px auto", padding: 20 }}>
      <h1 style={{ fontSize: 42 }}>DocPilot AI Demo</h1>
      <p>Generate a sample business document in seconds.</p>

      <div style={{ marginTop: 25 }}>
        <label>
          <b>Document type</b>
        </label>
        <select
          value={docType}
          onChange={(e) => setDocType(e.target.value)}
          style={{ width: "100%", padding: 12, marginTop: 8 }}
        >
          <option>Business Proposal</option>
          <option>Invoice</option>
          <option>Business Letter</option>
          <option>Simple Contract</option>
        </select>
      </div>

      <div style={{ marginTop: 25 }}>
        <label>
          <b>Language</b>
        </label>
        <select
          value={language}
          onChange={(e) => setLanguage(e.target.value)}
          style={{ width: "100%", padding: 12, marginTop: 8 }}
        >
          <option>English</option>
          <option>German</option>
          <option>Polish</option>
          <option>Ukrainian</option>
        </select>
      </div>

      <div style={{ marginTop: 25 }}>
        <label>
          <b>Company name</b>
        </label>
        <input
          value={companyName}
          onChange={(e) => setCompanyName(e.target.value)}
          placeholder="Your company name"
          style={{ width: "100%", padding: 12, marginTop: 8 }}
        />
      </div>

      <div style={{ marginTop: 25 }}>
        <label>
          <b>Client name</b>
        </label>
        <input
          value={clientName}
          onChange={(e) => setClientName(e.target.value)}
          placeholder="Client name"
          style={{ width: "100%", padding: 12, marginTop: 8 }}
        />
      </div>

      <div style={{ marginTop: 25 }}>
        <label>
          <b>Details</b>
        </label>
        <textarea
          value={details}
          onChange={(e) => setDetails(e.target.value)}
          placeholder="Describe what you need (project details, amount, deadlines, etc.)"
          style={{
            width: "100%",
            padding: 12,
            marginTop: 8,
            minHeight: 120,
          }}
        />
      </div>

      <div style={{ marginTop: 25 }}>
        <button
          onClick={generateDemo}
          style={{
            padding: "14px 22px",
            fontSize: 16,
            cursor: "pointer",
          }}
        >
          Generate Document (Demo)
        </button>

        <a href="/" style={{ marginLeft: 20 }}>
          Back to Home
        </a>
      </div>

      {result && (
        <div style={{ marginTop: 40 }}>
          <h2>Generated document</h2>
          <textarea
            value={result}
            readOnly
            style={{
              width: "100%",
              minHeight: 260,
              padding: 12,
              background: "#f5f5f5",
            }}
          />

          <div style={{ marginTop: 20 }}>
            <p style={{ fontSize: 16 }}>
              Want UK legal templates + DOCX download?{" "}
              <a href="/pricing">
                <b>Upgrade here → Pricing</b>
              </a>
            </p>
          </div>
        </div>
      )}
    </div>
  );
}

