import { useState } from "react";

export default function Demo() {
  const [docType, setDocType] = useState("Business Proposal");
  const [lang, setLang] = useState("EN");
  const [company, setCompany] = useState("");
  const [client, setClient] = useState("");
  const [details, setDetails] = useState("");
  const [result, setResult] = useState("");

  function generateDoc() {
    const date = new Date().toLocaleDateString();

    let title = "";
    let body = "";

    if (lang === "EN") {
      title = `${docType}`;
      body = `
Date: ${date}

Company: ${company || "________________"}
Client: ${client || "________________"}

DOCUMENT TYPE: ${docType}

Details:
${details || "________________"}

Generated by DocPilot AI (Demo Version).
This demo document is generated automatically and should be reviewed before official use.
      `;
    }

    if (lang === "UA") {
      title = `${docType} (Українська версія)`;
      body = `
Дата: ${date}

Компанія: ${company || "________________"}
Клієнт: ${client || "________________"}

ТИП ДОКУМЕНТА: ${docType}

Деталі:
${details || "________________"}

Згенеровано DocPilot AI (Демо).
Документ потрібно перевірити перед офіційним використанням.
      `;
    }

    if (lang === "PL") {
      title = `${docType} (Wersja Polska)`;
      body = `
Data: ${date}

Firma: ${company || "________________"}
Klient: ${client || "________________"}

TYP DOKUMENTU: ${docType}

Szczegóły:
${details || "________________"}

Wygenerowane przez DocPilot AI (Demo).
Dokument należy sprawdzić przed oficjalnym użyciem.
      `;
    }

    if (lang === "DE") {
      title = `${docType} (Deutsche Version)`;
      body = `
Datum: ${date}

Firma: ${company || "________________"}
Kunde: ${client || "________________"}

DOKUMENTTYP: ${docType}

Details:
${details || "________________"}

Erstellt von DocPilot AI (Demo).
Dieses Dokument sollte vor der offiziellen Nutzung geprüft werden.
      `;
    }

    if (lang === "FR") {
      title = `${docType} (Version Française)`;
      body = `
Date : ${date}

Entreprise : ${company || "________________"}
Client : ${client || "________________"}

TYPE DE DOCUMENT : ${docType}

Détails :
${details || "________________"}

Généré par DocPilot AI (Démo).
Ce document doit être vérifié avant toute utilisation officielle.
      `;
    }

    setResult(title + "\n\n" + body);
  }

  return (
    <div style={{ maxWidth: 900, margin: "40px auto", fontFamily: "Arial", padding: "0 20px" }}>
      <h1>DocPilot AI Demo</h1>
      <p>Generate a sample business document in seconds.</p>

      <div style={{ marginTop: 20 }}>
        <label><b>Document type</b></label>
        <br />
        <select
          value={docType}
          onChange={(e) => setDocType(e.target.value)}
          style={{ padding: 10, width: "100%", marginTop: 8 }}
        >
          <option>Business Proposal</option>
          <option>Invoice</option>
          <option>Service Agreement</option>
          <option>NDA</option>
          <option>Complaint Letter</option>
          <option>Cover Letter</option>
        </select>
      </div>

      <div style={{ marginTop: 20 }}>
        <label><b>Language</b></label>
        <br />
        <select
          value={lang}
          onChange={(e) => setLang(e.target.value)}
          style={{ padding: 10, width: "100%", marginTop: 8 }}
        >
          <option value="EN">English</option>
          <option value="UA">Українська</option>
          <option value="PL">Polski</option>
          <option value="DE">Deutsch</option>
          <option value="FR">Français</option>
        </select>
      </div>

      <div style={{ marginTop: 20 }}>
        <label><b>Company name</b></label>
        <br />
        <input
          value={company}
          onChange={(e) => setCompany(e.target.value)}
          placeholder="Your company name"
          style={{ padding: 10, width: "100%", marginTop: 8 }}
        />
      </div>

      <div style={{ marginTop: 20 }}>
        <label><b>Client name</b></label>
        <br />
        <input
          value={client}
          onChange={(e) => setClient(e.target.value)}
          placeholder="Client name"
          style={{ padding: 10, width: "100%", marginTop: 8 }}
        />
      </div>

      <div style={{ marginTop: 20 }}>
        <label><b>Details</b></label>
        <br />
        <textarea
          value={details}
          onChange={(e) => setDetails(e.target.value)}
          placeholder="Describe what you need (project details, amount, deadlines, etc.)"
          style={{ padding: 10, width: "100%", marginTop: 8, minHeight: 120 }}
        />
      </div>

      <div style={{ marginTop: 20 }}>
        <button
          onClick={generateDoc}
          style={{ padding: "14px 24px", fontSize: 16, cursor: "pointer" }}
        >
          Generate Document (Demo)
        </button>

        <a href="/" style={{ marginLeft: 20 }}>
          Back to Home
        </a>
      </div>

      {result && (
        <div style={{ marginTop: 40 }}>
          <h2>Generated Document</h2>
          <pre style={{
            whiteSpace: "pre-wrap",
            background: "#f5f5f5",
            padding: 20,
            borderRadius: 10
          }}>
            {result}
          </pre>
        </div>
      )}
    </div>
  );
}
