export default function Terms() {
  return (
    <div style={{maxWidth:800, margin:"40px auto", fontFamily:"Arial"}}>
      <h1>Terms of Service</h1>
      <p>Last updated: 2026-03-26</p>

      <p>
        DocPilot AI provides AI-generated documents. By using this service, you agree
        to these terms.
      </p>

      <h2>Service Disclaimer</h2>
      <p>
        Documents generated by AI are provided for informational purposes only and
        do not constitute legal advice.
      </p>

      <h2>User Responsibility</h2>
      <p>
        You are responsible for verifying the generated content before using it for
        business or legal purposes.
      </p>

      <h2>Refund Policy</h2>
      <p>
        Refunds are provided only if the service is not delivered.
      </p>

      <h2>Contact</h2>
      <p>
        Email: support@yourdomain.com
      </p>
    </div>
  );
}
